[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal]
shell = { program = "/usr/bin/zsh" }

[window]
dimensions = { columns = 100, lines = 30 }
dynamic_padding = true
decorations = "None"
opacity = 0.85
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "SF Mono" }
bold = { family = "SF Mono" }
italic = { family = "SF Mono" }
bold_italic = { family = "SF Mono" }
size = 11.5

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Off" }
unfocused_hollow = true
