config_version = 13

[dock]
enabled = true
icon_size = 28
pinned = [ "brave-origin", "dev.noctalia.Noctalia" ]
reserve_space = false
show_dots = true
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 683.0
    cy = 586.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
avatar_path = "/home/rodwell/Pictures/walls/hiyuki_profile.jpg"

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    clipboard_placement = "attached"
    polkit_placement = "attached"
    transparency_mode = "glass"

[theme]
builtin = "Kanagawa"
community_palette = "ADW"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "niri", "starship" ]
    community_ids = [ "whitesur-icons" ]

[wallpaper]
directory = "/home/rodwell/Pictures/walls"

    [wallpaper.default]
    path = "/home/rodwell/Pictures/walls/26668334.png"

    [wallpaper.last]
    path = "/home/rodwell/Pictures/walls/26668334.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/rodwell/Pictures/walls/26668334.png"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/rodwell/Pictures/walls/26668334.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"